# Generated by Django 3.1.4 on 2020-12-18 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('unit_number', models.IntegerField(verbose_name='Unit Number')),
                ('available', models.BooleanField(verbose_name='is this apartment available?')),
                ('rent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptlist.apartment')),
            ],
        ),
    ]
