# Generated by Django 3.1.4 on 2020-12-18 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='date_built',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date built'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='date_rented',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date rented'),
        ),
    ]
