# Generated by Django 3.1.4 on 2020-12-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptlist', '0002_auto_20201218_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='date_rented',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date rented'),
        ),
    ]
