# Generated by Django 3.1.4 on 2020-12-19 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aptlist', '0003_auto_20201218_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_rented', models.DateTimeField(blank=True, null=True, verbose_name='date rented')),
            ],
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='available',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='date_rented',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='lease',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptlist.apartment'),
        ),
    ]
