# Generated by Django 3.1.4 on 2020-12-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptlist', '0005_lease_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='active',
        ),
    ]
