# Generated by Django 3.1.4 on 2020-12-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptlist', '0006_remove_lease_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='date_rented',
            new_name='lease_expires',
        ),
    ]
