# Generated by Django 3.1.4 on 2020-12-21 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptlist', '0007_auto_20201221_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='lease_expires',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='lease expires'),
        ),
    ]
