# Generated by Django 3.1.4 on 2020-12-21 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aptlist', '0008_auto_20201221_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='date_built',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 19, 1, 4, 7284, tzinfo=utc), verbose_name='date built'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='lease_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 19, 1, 4, 30309, tzinfo=utc), verbose_name='lease expires'),
        ),
    ]
