# Generated by Django 3.1.4 on 2020-12-21 19:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aptlist', '0010_auto_20201221_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='lease_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 19, 14, 28, 127748, tzinfo=utc), verbose_name='lease expires'),
        ),
    ]
